### ISSUE TITLE
Building firmware via platformio

### ISSUE THREAD

**Issue by brightproject** [finani/ICM42688#20]
I work in `vscode + platformio`.
When assembling the project, I encountered interesting indications of frequency numbers and other things, I had never encountered such indication of numbers before, even working in the `Arduino IDE` environment.

> .pio/libdeps/ESP-WROOM-32/ICM42688/src/ICM42688.cpp:1022:39: warning: missing terminating ' character
>   float       Fdrv                 = 19'200 / (clkdiv * 10.0f);          // in kHz  (19.2MHz = 19200 kHz)

An example of some lines below, an apostro is written everywhere in the numbers - why is this done?

> 	// float       Fdrv                 = 19'200 / (clkdiv * 10.0f);          // in kHz  (19.2MHz = 19200 kHz)
> 	float       Fdrv                 = 19200 / (clkdiv * 10.0f);          // in kHz  (19.2MHz = 19200 kHz)

**Comment by finani** [comment]
It was used to make numbers easier to read.
This feature was added at C++14 and the reference is [here](https://en.cppreference.com/w/cpp/language/integer_literal). 
Does an error occur when building?

**Comment by brightproject** [comment]
> Does an error occur when building?

Thanks for the explanation.
The firmware is now being built and the code is working.
I am getting the acceleration and angular velocity data I need.
The apostrophe in the numbers was not recognized by my compiler.
