### ISSUE TITLE
Issue with SPI mode for mikroe-4237 board ( ICM42688-p )

### ISSUE THREAD

**Issue by jlja18** [finani/ICM42688#3]
If you get an error in the simple SPI example on the very first read, change the SPI mode to mode3 in the source code.

**Comment by plusk01** [comment]
It seems like the SPI mode should be set as `SPI_MODE3` for all masters/boards. Looking at Section 9.6 of [the datasheet](https://invensense.wpenginepowered.com/wp-content/uploads/2022/12/DS-000347-ICM-42688-P-v1.7.pdf), data is latched on the rising edge of SCLK, which is either MODE0 or MODE3. Looking at Section 3.5 of the datasheet shows that an inactive clock should be pulled high, which is either MODE2 or MODE3. Therefore, `SPI_MODE3` is the appropriate choice.

![image](https://user-images.githubusercontent.com/3934603/210916948-eee1c579-ed3b-4ef7-8f3d-35d4d75af168.png)


See the following for more info on SPI modes: https://www.corelis.com/education/tutorials/spi-tutorial/

![image](https://user-images.githubusercontent.com/3934603/210916837-d2fe9220-1c5c-44e3-bc59-076ffd4bf1db.png)

tested on esp32

**Comment by finani** [comment]
Thank you for the issues and the reply.
I tested the repo with teensy 4.0. So, It would be a little different at other boards.
